### ISSUE TITLE
invalid option: --verbose

### ISSUE THREAD

**Issue by dariusj18** [timdouglas/sublime-less2css#103]
error: /Library/Ruby/Gems/2.0.0/gems/less-2.6.0/bin/lessc:83:in `<top (required)>': invalid option: --verbose (OptionParser::InvalidOption)
    	from /usr/bin/lessc:23:in `load'
    	from /usr/bin/lessc:23:in `<main>'

**Comment by lubosmachaj** [comment]
Same problem here. Started after I installed the `less` gem.

**Comment by mattseymour** [comment]
If this is still an issue we can create a patch do people still use ruby-less?

**Comment by twentyfortysix** [comment]
same here

/Library/Ruby/Gems/2.0.0/gems/less-2.2.2/bin/lessc:81:in `<top (required)>': invalid option: --verbose (OptionParser::InvalidOption)
	from /usr/bin/lessc:23:in `load'
	from /usr/bin/lessc:23:in `<main>'

**Comment by mattseymour** [comment]
@twentyfortysix this will shortly be in the main project.
