### ISSUE TITLE
Cannot compile, asking to install less-plugin-clean-css

### ISSUE THREAD

**Issue by digitalac3** [timdouglas/sublime-less2css#105]
I installed ST3 along with less2css and node.js with less in my new computer. When I try to compile the less file I get this error message. "The compress option has been deprecated. We recommend you use a  dedicated css minifier, for instance see less-plugin-clean-css"

I tried installing that plugin also. But I still get the same error. Any ideas?

**Comment by n8sb** [comment]
Same issue.  My work around was to set  "minify": false in the less2css user settings, which means currently no minification, but at least it "works".

**Comment by pascaliske** [comment]
I've installed less in node.js and use it with less2css in ST3. It sounds weird but this issue here doesn't appears on my machine... I can compile less to css with this plugin and also minifying...

**Comment by pascaliske** [comment]
@n8sb I understand, this makes sense! Thank you.

**Comment by digitalac3** [comment]
@n8sb yeah :S. It works without minifying. Which my current project requires. I'm currently using SimpLESS application. Hope this would get fixed soon. I don't like using some other tool when you can do it with ST.

**Comment by pascaliske** [comment]
@digitalac3 Yeah, it is a lot easier and faster when we can do everything in ST!

**Comment by digitalac3** [comment]
I hope this issue will get fixed soon. :)

**Comment by cbtposborne** [comment]
I have the same issue but when I installed less with NPM now it doesn't compile at all.

**Comment by digitalac3** [comment]
@cbtposborne You can still compile without minifying though. But I really need the minifier :(

**Comment by abule** [comment]
Same issue here! I want to set minify to true

**Comment by Fluik** [comment]
I came up with solution. You need to install less-plugin-clean-css and change few lines of less2css file lesscompiler.py.

There is condition "if minimised:" on line 182, change next line to 
>cmd = [lessc_command, less, css, '--clean-css="--s1 --advanced --compatibility=ie8"', "--verbose"]

and delete this 
>if platform_name == 'Windows':
>        cmd[3] = '-compress'

I'm on Win7 and it's working fine.

**Comment by WEGIII** [comment]
For Windows:

if platform_name == 'Windows':
cmd[3] = '-compress'

change to:

if platform_name == 'Windows':
cmd[3] = '--clean-css'

Worked like a charm!

**Comment by leafiy** [comment]
where can i find lesscompiler.py, there is only  Less2Css.sublime-package i can find in Installed packages

**Comment by mike-anthony** [comment]
@leafiy - If you install the package with Package Control, the file doesn't exist (it's packaged). You'll need to uninstall the package, and then clone the repo into your packages directory. Then you can change the py file.

**Comment by Fluik** [comment]
You can install "PackageResourceViewer" to view the file.

**Comment by LolaYan** [comment]
https://github.com/NickWoodhams/sublime-less2css/commit/68ede6ebe61770aa08138071c74803719a0ad064
fixed with this method.

**Comment by mqliutie** [comment]
WOW, I have solved this problem.Set `minify` to false . HAHA!!!!

**Comment by leafiy** [comment]
OSX / Ubuntu
I have installed less-plugin-clean-css with npm -g, but the 'deprecated' warning still there, no one fixed this for 6 months?

**Comment by mattseymour** [comment]
This issue has been fixed #117
