### ISSUE TITLE
error message when set "minify": true

### ISSUE THREAD

**Issue by worrawutp** [timdouglas/sublime-less2css#107]
I got error "The compress option has been deprecated. We recommend you use a dedicated css minifier, for instance see less-plugin-clean-css"

It works ok when set minify: false

**Comment by umutgumeli** [comment]
I have this too

**Comment by Fluik** [comment]
Try solution here https://github.com/timdouglas/sublime-less2css/issues/105#issuecomment-72633458

**Comment by mattseymour** [comment]
Issue fixed in #117
