### ISSUE TITLE
[WARNING] Please install gem 'therubyracer' to use Less.

### ISSUE THREAD

**Issue by geniuspro** [timdouglas/sublime-less2css#115]
[WARNING] Please install gem 'therubyracer' to use Less.
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- v8 (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.6.0/lib/less/java_script.rb:9:in `default_context_wrapper'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.6.0/lib/less/java_script.rb:17:in `context_wrapper'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.6.0/lib/less/loader.rb:13:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.6.0/lib/less.rb:14:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.6.0/lib/less.rb:14:in `<module:Less>'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.6.0/lib/less.rb:9:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/less-2.6.0/bin/lessc:3:in `<top (required)>'
	from /usr/bin/lessc:23:in `load'
	from /usr/bin/lessc:23:in `<main>'

How can i fix it? I'm using Sublime Text 3 on MAC Yosemite 10.10.4

**Comment by mattseymour** [comment]
@olziinaa I have no experience with ruby what so ever. You might be better asking this question on SOF

**Comment by twentyfortysix** [comment]
I actuall yhae done it.. insttall the rubbyracer and since then when I save the less file this error pops up:
/Library/Ruby/Gems/2.0.0/gems/less-2.2.2/bin/lessc:81:in `<top (required)>': invalid option: --verbose (OptionParser::InvalidOption)
	from /usr/bin/lessc:23:in `load'
	from /usr/bin/lessc:23:in `<main>'

MAC OS 10.10.5, ST3
