### ISSUE TITLE
Relative path

### ISSUE THREAD

**Issue by selahssea-zz** [timdouglas/sublime-less2css#12]
Hi,

In Windows 7 I set 

``` javascript
"outputDir": "../css"
```

and it save file to 

``` javascript
"outputDir": "../css/less"
```

How can i change the settings for compile less files to only outputDir without "/less" adding?
Thank you.

**Comment by re2005** [comment]
it's possible to have multiple OUTPUT folder ?

Like:

		"less2css":
		{

			"lesscCommand": false,
			"lessBaseDir": "./",
			//"outputDir": "./",
			"outputDir": "path_one/subpath_one/",
			"outputDir": "path_two/subpath_two",
			"outputDir": "path_three/subpath_three",
			"outputFile": "file.css",
			"autoCompile": true,
			"main_file": "main.less"
		}


Thanks!
