### ISSUE TITLE
LESS2CSS NOT WORKING

### ISSUE THREAD

**Issue by Heash** [timdouglas/sublime-less2css#120]
Less2css extention does not compiling any LESS files and does not say any error after the last update. (Ubuntu Linux)

**Comment by mattseymour** [comment]
Care to expand on what is not working?

**Comment by Heash** [comment]
Updated the descrition of issue.

**Comment by mattseymour** [comment]
What version of sublime are you using?

**Comment by Heash** [comment]
Sublime text 3

**Comment by mattseymour** [comment]
Can you please run the equivalent command in command line and see if that gives you any additional information?

**Comment by Heash** [comment]
"lessc style.less style.css" works fine as for me from command line and compiles the css file.

**Comment by Heash** [comment]
Thanks, it's work now after some modifications in config file and "npm install -g less-plugin-clean-css" (I dont know what form that repears the extention)
