### ISSUE TITLE
plugin is not creating CSS files since upgrade

### ISSUE THREAD

**Issue by MladenJanjetovic** [timdouglas/sublime-less2css#121]
Windows 10 / Sublime 2

This is happening since new upgrade, in last few days.
No error. Just won't save css file.
Tried to reset sublime, reinstal package, change the settings for minimize, change dirs...nothing.

This is from commend line:
```
Writing file /C/blabla/public/css/public.less with encoding UTF-8
[less2css] Using minifier : --clean-css
[less2css] Converting C:\blabla\public\css\public.less to C:\blabla\public\css\public.min.css
[less2css] Convert completed!
```

**Comment by mattseymour** [comment]
You probably need to install do the following http://lesscss.org/usage/#command-line-usage-clean-css (https://github.com/less/less-plugin-clean-css)

**Comment by mattseymour** [comment]
Or set `minify="-compress"`on windows OS's

**Comment by MladenJanjetovic** [comment]
I instaled the plugin, but it didn't work.
`minify="-compress"` did the trick! 

Thanks!

**Comment by mattseymour** [comment]
Okay i will patch this in the code. Thanks for bringing it to my attention.

**Comment by MladenJanjetovic** [comment]
Glad to help.
