### ISSUE TITLE
autocomplie failing if minify set true

### ISSUE THREAD

**Issue by hozefaj** [timdouglas/sublime-less2css#127]
I am using the package on Sublime text 3(build 3083), on Mac running OS X Yosemite(10.10.5) and for the following user setting `atuocompile` fails

```json
{
    "minify":true,
    "outputDir":"shadow",
    "autoCompile":true
}
```

However, if I change the `minify` option to `false`  auto compiling works again.

**Comment by mattseymour** [comment]
I am looking into this issue but I cannot replicate with the given information. Are you getting any errors?

**Comment by hozefaj** [comment]
I don't see any errors. But definitely the `less` file is not getting complied.
```
[less2css] Using minifier : --clean-css
[less2css] Converting /Users/hjodiawalla/Desktop/My-Projects/projects/scripts/test.less to /Users/hjodiawalla/Desktop/My-Projects/projects/scripts/test.css
[less2css] Convert completed!
```

**Comment by fostonda** [comment]
In Sublime Text 2, with minify set to true one gets the following error: 'Unable to interpret argument clean-css - if it is a plugin (less-plugin-clean-css), make sure that it is installed under or at the same level as less'.

Setting minify to false allows compilation ok.

**Comment by hozefaj** [comment]
Issue resolved by either setting `minify: false` or installing `less-plugin-clean-css` plugin
