### ISSUE TITLE
The plugin suddenly becomes invalid today.

### ISSUE THREAD

**Issue by vrbvillor** [timdouglas/sublime-less2css#134]
I installed all the less/less2css/less-build/lessc in sublime,  It also no effect whether I use ALT+S or click the tools menu item Less->css

Help,OMG.....  T-T

**Comment by vrbvillor** [comment]
It can work last week,  but no response today.   I uninstalled all related plugins and reinstall them all......but nothing changes....

**Comment by Fluik** [comment]
You need to edit less2css.py. There is change in name of function.On line 57 change it to 
resp = l2c.convertOne(is_auto_save=True)

**Comment by mattseymour** [comment]
This should now be fixed, a function alias was added between convertOne and newly named convert_one.
