### ISSUE TITLE
/usr/bin/env - error - linux

### ISSUE THREAD

**Issue by twentyfortysix** [timdouglas/sublime-less2css#23]
Hello

mu Xubuntu 12.04 produces this error:
Writing file /home/jm/TMP/less/test.less with encoding UTF-8
[less2css] Converting /home/jm/TMP/less/test.less to /home/jm/TMP/less/test.css
----[less2cc] Compile Error----
/usr/bin/env: node: No such file or directory

but the env file exists. I have tried to run the sublime as root with the same result.

**Comment by Mao8a** [comment]
Solved on Mac OS X Yosemite using [this](https://github.com/timdouglas/sublime-less2css/issues/55#issuecomment-99960778)
