### ISSUE TITLE
less2css error: `lessc` is not avavailable

### ISSUE THREAD

**Issue by kanitw** [timdouglas/sublime-less2css#55]
1) I can run `lessc` from my terminal.  Do you have any idea why it is not available in sublime?

2) your error message has typo errors (should be **available**–not *avavailable*)

**Comment by Mao8a** [comment]
using @PGBI On Mac OS X Yosemite:
Useful to know: `which node` and `which lessc`
To make it work :
* Add `"lesscCommand": "/Users/<yourusername>/.node/bin/lessc",` line to Preferences > Package Settings > Less2Css > Settings User

[Source](https://scotch.io/bar-talk/the-complete-visual-guide-to-sublime-text-3-plugins-part-2)

If error : "env: node: No such file or directory"
then :
 'sudo ln -s /usr/local/bin/node /usr/bin/node'

**Comment by Redeye1** [comment]
less2css error: [Errno 2] No such file or directory

I have tried to install with node and npm
Have followed instructions from here, http://tech.diaslopes.com/?p=112
still getting the error above
Any ideas?

**Comment by ladik** [comment]
God bless you @PGBI ! 

With a slight edit it worked for me on Mac OS X 10.10.3

```
sudo ln -s /opt/local/bin/lessc /usr/bin/lessc
sudo ln -s /opt/local/bin/node /usr/bin/node
```

**Comment by mqliutie** [comment]
@Mao8a  Thanks, I have solved this problem with your help. But there have a tip **"The compress option has been deprecated. We recommend you use a dedicated css minifier, for instance see less-plugin-clean-css."**  The reason I have `env: node: No such file or directory` problem is I installed `less-plugin-clean-css`. Befor installing it , I can do it well just have this tip. After installing it I meet `env: node: No such file or directory` problem . How to solve it? Thanks

**Comment by quinnstinchurchill** [comment]
Hey guys, I'm running into the same issue. I'm just wondering how one would print the `$PATH` from sublime's perspective. Thanks in advance :)

**Comment by mattseymour** [comment]
Open sublime console, then do `import sys` followed by `sys.path`

**Comment by monkindey** [comment]
@Mao8a 
`osx` version >= 10.11, can't `ln`, the error is 
```sh
ln: /usr/bin/node: Operation not permitted
```

because i use the `ST3`, i use [packageResourceView](https://github.com/skuroda/PackageResourceViewer) and open the `lessc` source，
and motify the **lessc.sublime-build**

```json
{
    "cmd": ["lessc", "-x", "$file", "${file_path}/${file_base_name}.css", "--source-map", "--verbose"],
    "file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
    "selector": "source.css.less",
    "osx":
    {
        "path": "/Users/monkindey/.nvm/versions/node/v4.4.0/bin:$PATH"
    },

    "windows":
    {
        "cmd": ["lessc.cmd", "-x", "$file", "${file_base_name}.css", "--source-map"]
    },

    "variants": [
        {
            "name": "Non-Minified",
            "cmd": ["lessc",  "", "$file", "${file_path}/${file_base_name}.min.css", "--source-map", "--verbose"],

            "osx":
            {
                "path": "/usr/local/bin:$PATH"
            },
            "windows":
            {
                "cmd": ["lessc.cmd", "", "$file", "${file_base_name}.css", "--source-map"]
            }
        }
    ]
}

```
the **osx** config , is your node path.

it work for me, hopely work for you too

sorry , my English is poor.
THX

**Comment by shoppyonline** [comment]
Hi @monkindey,

Please exactly can I find the lessc.sublime-build file to modify?
I have been battling this same problem since Friday and it's been my first week on the job with a new mac version 10.11.6. I use ST3 as well.

Sorry I don't know python. I just want to solve this issue and move on with the less conversions.
Please help.

Thanks.

**Comment by monkindey** [comment]
@shoppyonline 

1.  ST3 download the **[PackageResourceViewer](https://github.com/skuroda/PackageResourceViewer)**

2. exec PackageResourceViewer: Open Resource

3. input the **lessc**

4. you can find the **lessc.sublime-build**

hopely work for you.....

**Comment by shoppyonline** [comment]
@monkindey 
Thanks for your quick reply.

I think I see a problem already.
I don't seem to have **lessc** in my menu. When I type less all that popups up is **Less2css**.
Am I getting this all wrong?

**Comment by monkindey** [comment]
@shoppyonline

![image](https://cloud.githubusercontent.com/assets/6913898/19228463/167d9710-8ef8-11e6-950d-e9f098199c2e.png)

Can you find **lessc** ?

**Comment by shoppyonline** [comment]
Nope, I can't find lessc.

<img width="455" alt="screen shot 2016-10-10 at 7 48 09 am" src="https://cloud.githubusercontent.com/assets/1023848/19228523/02a7d3ac-8ebe-11e6-8eb2-002debb5db43.png">

**Comment by monkindey** [comment]
@shoppyonline  you may need to install **lessc** with the **Package Control**

Because my English is **poor** and doesn't dive into how the sublime work, So I afraid not 
help you more. Sorry, Please forgive me.

**Comment by shoppyonline** [comment]
Thanks @monkindey for your help.
