### ISSUE TITLE
lessc command flags

### ISSUE THREAD

**Issue by juanojeda** [timdouglas/sublime-less2css#59]
Hey there,
Is there an option to specify command flags on the lessc command? I tried by modifying the lesscCommand parameter, but that seems to be for something completely different.
What I'm trying to do, specifically, is enable Source Mapping in Chrome with `lessc --linenumbers=mediaquery [src] [output]` as explained in [this post](http://robdodson.me/blog/2012/12/28/debug-less-with-chrome-developer-tools/), but I'm sure there are other flags that would be helpful to others, as well.

Also, thanks for the awesome plugin!

**Comment by gkatsanos** [comment]
+1

**Comment by pascaliske** [comment]
The sourcemap setting is already added! You can add the setting. Here is my settings file:
[https://www.dropbox.com/s/7t4z3vfojz2xsv4/less2css.sublime-settings?dl=0](Settings-file Dropbox)

**Comment by gkatsanos** [comment]
@pascaliske 404 NOT FOUND :(

**Comment by pascaliske** [comment]
@gkatsanos Mhm wait. I post the contents of the file as a comment. :D

**Comment by pascaliske** [comment]
Here it is:

{
	"minName": true,
	"main_file": "main.less",
	"ignorePrefixedFiles": true,
	"createCssSourceMaps": true
}

**Comment by gkatsanos** [comment]
@pascaliske  any idea where the map files are saved? I just triggered a save but they don't seem to be generated

**Comment by pascaliske** [comment]
the map file is saved in the same folder as the main less file and the compiled and compressed CSS file..

**Comment by gkatsanos** [comment]
See my settings below; I don't see the map files.. - they're not generated
```
{
  "lesscCommand": false,
  "lessBaseDir": "./",
  "outputDir": "/Users/Georgios/Development/rocket-internet/INTFARM/alice/public/local/css/local/compiled/",
  "outputFile": "", //[example.css] if left blank uses same name of .less file
  "minify": false,
  "minName": false,
  "autoCompile": true,
  "showErrorWithWindow": true,
  "main_file": false,
  "ignorePrefixedFiles": false,
  "createCssSourceMaps": true
}
```

**Comment by pascaliske** [comment]
Probably a source map only will be generated if you're using a main file in your project? Perhabs you can try using a main file in a test project? Let me know if it then functions properly!

**Comment by gkatsanos** [comment]
@pascaliske I added the main file, I trigger a save, I don't get any errors in the console: 
```
Writing file /Users/Georgios/Development/rocket-internet/INTFARM/alice/public/local/less/intfarm.less with encoding UTF-8
[less2css] Converting /Users/Georgios/Development/rocket-internet/INTFARM/alice/public/local/less/intfarm.less to /Users/Georgios/Development/rocket-internet/INTFARM/alice/public/local/css/local/compiled/intfarm.css
[less2css] Convert completed!
```
but no .map files..

Is there anyway to debug this? To see which command is executed etc? (I'm on a mac)

**Comment by pascaliske** [comment]
@gkatsanos Oh I noticed that the source maps are only generated on my imac, on my older macbook where I have nearly the same setup the source maps aren't generated!
I'm out of ideas right now! Sorry...
I check my setup on my imac later this week and let u know if I found the solution for our problem here!
Good night! :zzz: :sleeping:

**Comment by gkatsanos** [comment]
@pascaliske could you give me your working setup and why it's not working on the other one so I can debug this?:)

**Comment by pascaliske** [comment]
@gkatsanos I'm not at home because i'm in Winter vacation. But when i'm back in 3 day's I'll send you all config-files! :)
Can you give me your mail-address for that? Would be easier I think..

**Comment by gkatsanos** [comment]
Sure, george@gplus.gr

*Georgios Katsanos*
e: george@gplus.gr
t:  +49 (0) 1623282207
w: http://www.gplus.gr
skype: george.katsanos
linkedin: http://www.linkedin.com/in/georgekatsanos

**Comment by pascaliske** [comment]
The email is on its way, write if you don't get it! :)

**Comment by billyrennekamp** [comment]
any updates? having the same problem and would love to see less line numbers.

**Comment by mattseymour** [comment]
Source maps have just been added into the plugin. #83
