### ISSUE TITLE
LESS 1.5 with source-map generator

### ISSUE THREAD

**Issue by luiz-bonfa** [timdouglas/sublime-less2css#74]
Less 1.5 now allows to generate source map. Source map is easy to request by using parameters for lessc  compiler such as --source-map[=FILENAME]  But how to generate source map when we use less2css?

**Comment by vallieres** [comment]
++++ what's up with this PR? Will it be added to the main branch?

**Comment by quanru** [comment]
+10086

**Comment by mattseymour** [comment]
This has been merged into master https://github.com/timdouglas/sublime-less2css/pull/83
