### ISSUE TITLE
less2css stop working all of sudden for ST2 on a Mac

### ISSUE THREAD

**Issue by ronnyperez** [timdouglas/sublime-less2css#81]
So I installed less2css for sublime text 2 on my mac 2 or 3 days a go and everything was great until last night it stopped working it doesn't show me any errors or message prompt nothing it just stop working. Please help

**Comment by jezzaKratos** [comment]
same here

**Comment by jezzaKratos** [comment]
Possibly a syntax error in the less file... I compiled the less with another less compiler and found a bug. once i fixed the bug, less2css started working again.
