### ISSUE TITLE
less2css does not seem to see node lessC, compile fails

### ISSUE THREAD

**Issue by smlombardi** [timdouglas/sublime-less2css#91]
I installed less 1.7.x via NPM.  Run plugin.

I get an error:

error: /Library/Ruby/Gems/1.8/gems/less-2.0.12/bin/lessc:20:in `read': No such file or directory - -x (Errno::ENOENT)
	from /Library/Ruby/Gems/1.8/gems/less-2.0.12/bin/lessc:20
	from /usr/bin/lessc:19:in `load'
	from /usr/bin/lessc:19

Mac 10.9.2, Sublime 3 3059

**Comment by mattseymour** [comment]
lesscCommand should be a string value as per the readme, not a boolean. This has been fixed as in ticket #79
